### Get all products
GET http://localhost:8080/products


### Get product by ID
GET http://localhost:8080/products/5


### Create product
POST http://localhost:8080/products
Content-Type: application/json

{
  "name": "Laptop",
  "price": 2500
}